# Generated by Django 3.2.12 on 2022-05-16 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220515_2130'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skill',
            new_name='Skills',
        ),
    ]
