# Generated by Django 3.2.12 on 2022-05-16 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_skill_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='stackoverflow',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
