# Generated by Django 3.2.12 on 2022-05-16 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20220516_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='description_exact',
            field=models.TextField(blank=True, null=True),
        ),
    ]
