# Generated by Django 3.2.12 on 2022-05-16 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_skills_description_exact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='description_exact',
        ),
    ]
