# Generated by Django 3.2.12 on 2022-05-16 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_skills_description_exact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skills',
            new_name='Skill',
        ),
    ]
