# Generated by Django 3.2.12 on 2023-06-20 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_review_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-vote_ratio', '-vote_total', 'title']},
        ),
    ]
